### ISSUE TITLE
Linux Mint 17 Not working

### ISSUE THREAD

**Issue by Alex-Space** [3demax/vlc-clickpause#5]
Checkbox selected in Menu->View, but click/pouse on mouse not working. VLC 2.2.2

**Comment by 3demax** [comment]
Please take a look at first paragraph of the [README](https://github.com/3demax/vlc-clickpause/blob/master/README.md)

If you want the same functionality, go check out [nurupo's plugin page](https://github.com/nurupo/vlc-pause-click-plugin).
